services:
  postgres:
    image: postgres:16-alpine
    container_name: bear-sighting-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    volumes:
      - bear-sighting-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  bear-sighting-db-data:
