from sqlalchemy import Column, DateTime, Float, Integer, String

from database import Base


class BearSighting(Base):
    """
    Database table definition for bear sighting information.
    """

    # Table name
    __tablename__ = "bear_sightings"

    # --- Column definitions ---

    # ID (auto-increment)
    id = Column(Integer, primary_key=True, index=True)

    # Location (extracted by LLM)
    prefecture = Column(String, index=True)
    city = Column(String, index=True)

    # Latitude and longitude (determined by geocoding)
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)

    # Summary (generated by LLM)
    summary = Column(String)

    # Source data from newsapi
    source_url = Column(String, unique=True, index=True)
    image_url = Column(String, nullable=True)
    published_at = Column(DateTime, index=True)
